Sushi_Osaka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from Sushi_Osaka import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/all/', include('goods.urls', namespace='catalog')),  
    path('user/', include('users.urls', namespace='user')), 
    path('cart/', include('carts.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls'))
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/<slug:product_slug>/', views.cart_add, name='cart_add'),
    path('cart_change/<slug:product_slug>/', views.cart_change, name='cart_change'),
    path('cart_remove/<slug:product_slug>/', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

carts/models.py
from django.db import models
from users.models import User
from goods.models import Products


class CartQueryset(models.QuerySet):
    def total_price(self):
        return sum(cart.product_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0
        


class Cart(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.IntegerField(default=1, verbose_name='Количество')
    session_key = models.CharField(max_length=32, blank=True, null=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    
    class Meta:
        db_table = 'cart'
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'
        
    objects = CartQueryset.as_manager()
    
    def product_price(self):
        return round(self.product.sell_price() * self.quantity, 2)
    
    
    def __str__(self):
        return f'Корзина {self.user.username} | Товар {self.product.name} | Количество {self.quantity}'

carts/views.py
from django.shortcuts import render, redirect
from goods.models import Products
from carts.models import Cart

def cart_add(request, product_slug):
    product = Products.objects.get(slug=product_slug)
    
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)
        
        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)
    return redirect(request.META['HTTP_REFERER'])
            
def cart_change(request, product_slug):
    pass

def cart_remove(request, product_slug):
    pass

carts/templates/carts/includes/included_cart.html
{% load static %}


<div class="card mb-3 text-bg-light shadow-lg">
    {% for cart in carts %}
            <div class="card-header">
                <h5 class="card-title">{{ cart.product.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="row text-center">
                        <div class="col p-0">
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-dark btn-sm decrement" data-cart-id="" data-cart-change-url="">-</button>
                                </span>
                                <input type="text" class="form-control number" value="{{ cart.quantity }}" readonly>
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-dark btn-sm increment" data-cart-id="" data-cart-change-url="">+</button>
                                </span>
                            </div>
                        </div>
                        <div class="col p-0">
                            <p>x {{ cart.product.sell_price }} = </p>
                        </div>
                        <div class="col p-0">
                            <strong>{{ cart.product.price }} ₽</strong>
                        </div>
                        <div class="col p-0">
                            <a href="{% url "cart:cart_remove" cart.product.slug %}" class="remove-from-cart" data-cart-id="">
                                <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}" alt="Catalog Icon" width="16" height="16">
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
    
    {% endfor %}
</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Итого <strong>{{ carts.total_quantity }}</strong> товар(а) на сумму</p>
        <h4 class="float-left"><strong>{{ carts.total_price }} ₽</strong></h4>
    </div>
</div>